/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#b7b5b4",
        "inverse-primary": "#006d38",
        "secondary-fixed-dim": "#c8c6c5",
        "on-background": "#e1e3e3",
        "on-error": "#690005",
        "on-primary-container": "#00592d",
        "outline": "#889488",
        "secondary-fixed": "#e5e2e1",
        "on-surface-variant": "#bdcabc",
        "tertiary-fixed": "#ffdad2",
        "surface-dim": "#111414",
        "error": "#ffb4ab",
        "tertiary": "#ffcfc4",
        "secondary": "#c8c6c5",
        "surface-container-lowest": "#0c0f0f",
        "inverse-on-surface": "#2e3131",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#3a0b02",
        "inverse-surface": "#e1e3e3",
        "primary-container": "#68d38a",
        "surface-container": "#1d2020",
        "on-secondary-fixed": "#1b1b1c",
        "on-tertiary": "#561f12",
        "on-secondary-fixed-variant": "#474746",
        "background": "#111414",
        "on-primary-fixed": "#00210d",
        "primary-fixed": "#8df9ac",
        "surface": "#111414",
        "on-tertiary-container": "#793b2b",
        "on-tertiary-fixed-variant": "#723526",
        "surface-container-highest": "#323536",
        "tertiary-container": "#ffa893",
        "tertiary-fixed-dim": "#ffb4a2",
        "surface-container-low": "#191c1c",
        "on-primary-fixed-variant": "#005229",
        "on-primary": "#00391a",
        "primary-fixed-dim": "#71dc92",
        "surface-container-high": "#282a2b",
        "surface-bright": "#373a3a",
        "outline-variant": "#3e4a3f",
        "on-surface": "#e1e3e3",
        "surface-variant": "#323536",
        "on-error-container": "#ffdad6",
        "on-secondary": "#303030",
        "secondary-container": "#474746",
        "surface-tint": "#71dc92",
        "primary": "#84f0a4"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1200px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        "unit": "4px"
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono"],
        "label-md": ["Inter"],
        "display-lg-mobile": ["Sora"],
        "headline-md": ["Sora"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Sora"],
        "display-lg": ["Sora"]
      },
      fontSize: {
        "code-sm": ["0.875rem", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["0.875rem", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg-mobile": ["2.5rem", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-md": ["2rem", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["1rem", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-sm": ["1.5rem", { "lineHeight": "1.4", "fontWeight": "600" }],
        "display-lg": ["4.5rem", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
